const prefectureData = [
  {
    id: 1,
    name: "北海道",
    reading: "Hokkaido",
    capital: "札幌市",
    region: "北海道",
    neighbors: ["青森県"],
    specialties: ["夕張メロン", "ジンギスカン", "カニ", "乳製品"],
    spots: ["五稜郭", "知床", "函館山", "富良野"],
    relation: "日本最大の都道府県。青森県と青函トンネルで接続。"
  },
  {
    id: 2,
    name: "青森県",
    reading: "Aomori",
    capital: "青森市",
    region: "東北",
    neighbors: ["北海道", "岩手県", "秋田県"],
    specialties: ["りんご", "大間マグロ", "せんべい汁"],
    spots: ["弘前城", "十和田湖", "ねぶた祭り"],
    relation: "本州最北端。りんご生産量日本一。"
  },
  {
    id: 3,
    name: "岩手県",
    reading: "Iwate",
    capital: "盛岡市",
    region: "東北",
    neighbors: ["青森県", "宮城県", "秋田県"],
    specialties: ["わんこそば", "盛岡冷麺", "南部鉄器"],
    spots: ["中尊寺金色堂", "小岩井農場", "龍泉洞"],
    relation: "北海道に次いで2番目に広い面積を持つ。"
  },
  {
    id: 4,
    name: "宮城県",
    reading: "Miyagi",
    capital: "仙台市",
    region: "東北",
    neighbors: ["岩手県", "秋田県", "山形県", "福島県"],
    specialties: ["牛タン", "ずんだ餅", "笹かまぼこ"],
    spots: ["松島", "仙台城跡", "瑞鳳殿"],
    relation: "東北地方の中心都市である仙台市を持つ。"
  },
  {
    id: 5,
    name: "秋田県",
    reading: "Akita",
    capital: "秋田市",
    region: "東北",
    neighbors: ["青森県", "岩手県", "宮城県", "山形県"],
    specialties: ["きりたんぽ", "稲庭うどん", "いぶりがっこ"],
    spots: ["田沢湖", "角館", "男鹿半島"],
    relation: "秋田美人やなまはげで有名。"
  },
  {
    id: 6,
    name: "山形県",
    reading: "Yamagata",
    capital: "山形市",
    region: "東北",
    neighbors: ["宮城県", "秋田県", "福島県", "新潟県"],
    specialties: ["さくらんぼ", "米沢牛", "芋煮"],
    spots: ["立石寺（山寺）", "銀山温泉", "蔵王"],
    relation: "さくらんぼの生産量が日本一。"
  },
  {
    id: 7,
    name: "福島県",
    reading: "Fukushima",
    capital: "福島市",
    region: "東北",
    neighbors: ["宮城県", "山形県", "茨城県", "栃木県", "群馬県", "新潟県"],
    specialties: ["桃", "喜多方ラーメン", "赤べこ"],
    spots: ["鶴ヶ城", "猪苗代湖", "五色沼"],
    relation: "東北地方の南端。面積は北海道、岩手に次ぐ第3位。"
  },
  {
    id: 8,
    name: "茨城県",
    reading: "Ibaraki",
    capital: "水戸市",
    region: "関東",
    neighbors: ["福島県", "栃木県", "埼玉県", "千葉県"],
    specialties: ["納豆", "メロン", "ほしいも"],
    spots: ["偕楽園", "袋田の滝", "筑波山"],
    relation: "平野部が広く、農業産出額が高い。"
  },
  {
    id: 9,
    name: "栃木県",
    reading: "Tochigi",
    capital: "宇都宮市",
    region: "関東",
    neighbors: ["福島県", "茨城県", "群馬県", "埼玉県"],
    specialties: ["宇都宮餃子", "とちおとめ（いちご）", "かんぴょう"],
    spots: ["日光東照宮", "華厳の滝", "あしかがフラワーパーク"],
    relation: "日光東照宮などの世界遺産がある。"
  },
  {
    id: 10,
    name: "群馬県",
    reading: "Gunma",
    capital: "前橋市",
    region: "関東",
    neighbors: ["福島県", "栃木県", "埼玉県", "新潟県", "長野県"],
    specialties: ["こんにゃく", "下仁田ネギ", "焼きまんじゅう"],
    spots: ["草津温泉", "富岡製糸場", "伊香保温泉"],
    relation: "温泉地が多く、温泉大国と呼ばれる。"
  },
  {
    id: 11,
    name: "埼玉県",
    reading: "Saitama",
    capital: "さいたま市",
    region: "関東",
    neighbors: ["茨城県", "栃木県", "群馬県", "千葉県", "東京都", "山梨県", "長野県"],
    specialties: ["草加せんべい", "深谷ねぎ"],
    spots: ["鉄道博物館", "川越（小江戸）", "長瀞"],
    relation: "東京のベッドタウンとして人口が多い。"
  },
  {
    id: 12,
    name: "千葉県",
    reading: "Chiba",
    capital: "千葉市",
    region: "関東",
    neighbors: ["茨城県", "埼玉県", "東京都", "神奈川県"],
    specialties: ["落花生", "梨", "伊勢海老"],
    spots: ["東京ディズニーリゾート", "成田山新勝寺", "鴨川シーワールド"],
    relation: "成田国際空港があり、日本の空の玄関口。"
  },
  {
    id: 13,
    name: "東京都",
    reading: "Tokyo",
    capital: "新宿区",
    region: "関東",
    neighbors: ["埼玉県", "千葉県", "神奈川県", "山梨県"],
    specialties: ["東京ばな奈", "江戸前寿司", "もんじゃ焼き"],
    spots: ["東京タワー", "スカイツリー", "浅草寺"],
    relation: "日本の首都。政治・経済の中心地。"
  },
  {
    id: 14,
    name: "神奈川県",
    reading: "Kanagawa",
    capital: "横浜市",
    region: "関東",
    neighbors: ["東京都", "山梨県", "静岡県"],
    specialties: ["シウマイ", "小田原かまぼこ"],
    spots: ["横浜みなとみらい", "鎌倉大仏", "箱根温泉"],
    relation: "人口は東京に次ぐ第2位。横浜港がある。"
  },
  {
    id: 15,
    name: "新潟県",
    reading: "Niigata",
    capital: "新潟市",
    region: "中部",
    neighbors: ["山形県", "福島県", "群馬県", "富山県", "長野県"],
    specialties: ["コシヒカリ", "日本酒", "笹団子"],
    spots: ["佐渡島", "清津峡", "彌彦神社"],
    relation: "日本有数の米どころ。"
  },
  {
    id: 16,
    name: "富山県",
    reading: "Toyama",
    capital: "富山市",
    region: "中部",
    neighbors: ["新潟県", "石川県", "長野県", "岐阜県"],
    specialties: ["ます寿司", "寒ブリ", "白エビ"],
    spots: ["立山黒部アルペンルート", "黒部ダム", "五箇山"],
    relation: "北陸地方に位置し、製薬業が盛ん。"
  },
  {
    id: 17,
    name: "石川県",
    reading: "Ishikawa",
    capital: "金沢市",
    region: "中部",
    neighbors: ["富山県", "福井県", "岐阜県"],
    specialties: ["加賀友禅", "金箔", "カニ"],
    spots: ["兼六園", "金沢21世紀美術館", "ひがし茶屋街"],
    relation: "伝統工芸や加賀百万石の歴史がある。"
  },
  {
    id: 18,
    name: "福井県",
    reading: "Fukui",
    capital: "福井市",
    region: "中部",
    neighbors: ["石川県", "岐阜県", "滋賀県", "京都府"],
    specialties: ["越前ガニ", "羽二重餅", "ソースカツ丼"],
    spots: ["東尋坊", "恐竜博物館", "永平寺"],
    relation: "恐竜の化石発掘量が日本一。"
  },
  {
    id: 19,
    name: "山梨県",
    reading: "Yamanashi",
    capital: "甲府市",
    region: "中部",
    neighbors: ["埼玉県", "東京都", "神奈川県", "長野県", "静岡県"],
    specialties: ["桃", "ぶどう", "ほうとう"],
    spots: ["富士山", "河口湖", "富士急ハイランド"],
    relation: "富士山の北側に位置し、果物王国と呼ばれる。"
  },
  {
    id: 20,
    name: "長野県",
    reading: "Nagano",
    capital: "長野市",
    region: "中部",
    neighbors: ["群馬県", "埼玉県", "新潟県", "富山県", "山梨県", "岐阜県", "静岡県", "愛知県"],
    specialties: ["信州そば", "りんご", "おやき"],
    spots: ["善光寺", "松本城", "上高地"],
    relation: "海に面しておらず、多くの山岳リゾートがある。"
  },
  {
    id: 21,
    name: "岐阜県",
    reading: "Gifu",
    capital: "岐阜市",
    region: "中部",
    neighbors: ["富山県", "石川県", "福井県", "長野県", "愛知県", "三重県", "滋賀県"],
    specialties: ["飛騨牛", "富有柿", "鶏ちゃん"],
    spots: ["白川郷", "下呂温泉", "岐阜城"],
    relation: "日本のほぼ中央に位置する。"
  },
  {
    id: 22,
    name: "静岡県",
    reading: "Shizuoka",
    capital: "静岡市",
    region: "中部",
    neighbors: ["神奈川県", "山梨県", "長野県", "愛知県"],
    specialties: ["お茶", "うなぎパイ", "富士宮やきそば"],
    spots: ["富士山", "熱海温泉", "浜名湖"],
    relation: "お茶の生産量が日本一。"
  },
  {
    id: 23,
    name: "愛知県",
    reading: "Aichi",
    capital: "名古屋市",
    region: "中部",
    neighbors: ["長野県", "岐阜県", "静岡県", "三重県"],
    specialties: ["ひつまぶし", "味噌カツ", "手羽先"],
    spots: ["名古屋城", "熱田神宮", "レゴランド"],
    relation: "自動車産業が盛んで、製造品出荷額等が日本一。"
  },
  {
    id: 24,
    name: "三重県",
    reading: "Mie",
    capital: "津市",
    region: "近畿",
    neighbors: ["岐阜県", "愛知県", "滋賀県", "京都府", "奈良県", "和歌山県"],
    specialties: ["松阪牛", "伊勢海老", "赤福"],
    spots: ["伊勢神宮", "鈴鹿サーキット", "ナガシマスパーランド"],
    relation: "伊勢神宮があり、古くからお伊勢参りで賑わう。"
  },
  {
    id: 25,
    name: "滋賀県",
    reading: "Shiga",
    capital: "大津市",
    region: "近畿",
    neighbors: ["福井県", "岐阜県", "三重県", "京都府"],
    specialties: ["近江牛", "鮒寿司"],
    spots: ["琵琶湖", "彦根城", "延暦寺"],
    relation: "日本最大の湖、琵琶湖がある。"
  },
  {
    id: 26,
    name: "京都府",
    reading: "Kyoto",
    capital: "京都市",
    region: "近畿",
    neighbors: ["福井県", "三重県", "滋賀県", "大阪府", "兵庫県", "奈良県"],
    specialties: ["八ツ橋", "京漬物", "抹茶"],
    spots: ["清水寺", "金閣寺", "伏見稲荷大社"],
    relation: "千年の都として栄え、文化財が多い。"
  },
  {
    id: 27,
    name: "大阪府",
    reading: "Osaka",
    capital: "大阪市",
    region: "近畿",
    neighbors: ["京都府", "兵庫県", "奈良県", "和歌山県"],
    specialties: ["たこ焼き", "お好み焼き", "串カツ"],
    spots: ["大阪城", "ユニバーサル・スタジオ・ジャパン", "道頓堀"],
    relation: "西日本の中心都市。「天下の台所」と呼ばれた。"
  },
  {
    id: 28,
    name: "兵庫県",
    reading: "Hyogo",
    capital: "神戸市",
    region: "近畿",
    neighbors: ["京都府", "大阪府", "鳥取県", "岡山県", "徳島県"],
    specialties: ["神戸牛", "明石焼き", "日本酒（灘）"],
    spots: ["姫路城", "甲子園球場", "有馬温泉"],
    relation: "日本海と瀬戸内海の2つの海に面している。"
  },
  {
    id: 29,
    name: "奈良県",
    reading: "Nara",
    capital: "奈良市",
    region: "近畿",
    neighbors: ["三重県", "京都府", "大阪府", "和歌山県"],
    specialties: ["柿の葉寿司", "三輪そうめん"],
    spots: ["東大寺", "奈良公園", "法隆寺"],
    relation: "平城京などの古い歴史を持つ。"
  },
  {
    id: 30,
    name: "和歌山県",
    reading: "Wakayama",
    capital: "和歌山市",
    region: "近畿",
    neighbors: ["三重県", "大阪府", "奈良県"],
    specialties: ["みかん", "梅干し", "和歌山ラーメン"],
    spots: ["高野山", "アドベンチャーワールド", "熊野古道"],
    relation: "みかんや梅の生産が盛ん。"
  },
  {
    id: 31,
    name: "鳥取県",
    reading: "Tottori",
    capital: "鳥取市",
    region: "中国",
    neighbors: ["兵庫県", "島根県", "岡山県", "広島県"],
    specialties: ["二十世紀梨", "松葉ガニ"],
    spots: ["鳥取砂丘", "水木しげるロード"],
    relation: "日本で最も人口が少ない県。"
  },
  {
    id: 32,
    name: "島根県",
    reading: "Shimane",
    capital: "松江市",
    region: "中国",
    neighbors: ["鳥取県", "広島県", "山口県"],
    specialties: ["出雲そば", "しじみ"],
    spots: ["出雲大社", "松江城", "石見銀山"],
    relation: "神話の舞台として知られる。"
  },
  {
    id: 33,
    name: "岡山県",
    reading: "Okayama",
    capital: "岡山市",
    region: "中国",
    neighbors: ["兵庫県", "鳥取県", "広島県", "香川県"],
    specialties: ["桃", "マスカット", "きびだんご"],
    spots: ["岡山後楽園", "倉敷美観地区", "瀬戸大橋"],
    relation: "「晴れの国」と呼ばれるほど雨が少ない。"
  },
  {
    id: 34,
    name: "広島県",
    reading: "Hiroshima",
    capital: "広島市",
    region: "中国",
    neighbors: ["鳥取県", "島根県", "岡山県", "山口県", "愛媛県"],
    specialties: ["お好み焼き", "もみじ饅頭", "牡蠣"],
    spots: ["原爆ドーム", "宮島・厳島神社", "尾道"],
    relation: "中国地方の中心都市、広島市がある。"
  },
  {
    id: 35,
    name: "山口県",
    reading: "Yamaguchi",
    capital: "山口市",
    region: "中国",
    neighbors: ["島根県", "広島県", "福岡県", "愛媛県", "大分県"],
    specialties: ["ふぐ", "瓦そば"],
    spots: ["錦帯橋", "秋芳洞", "角島大橋"],
    relation: "本州の西端に位置する。"
  },
  {
    id: 36,
    name: "徳島県",
    reading: "Tokushima",
    capital: "徳島市",
    region: "四国",
    neighbors: ["兵庫県", "高知県", "愛媛県", "香川県"],
    specialties: ["すだち", "阿波尾鶏", "鳴門金時"],
    spots: ["鳴門の渦潮", "阿波おどり会館", "祖谷のかずら橋"],
    relation: "阿波おどりが有名。"
  },
  {
    id: 37,
    name: "香川県",
    reading: "Kagawa",
    capital: "高松市",
    region: "四国",
    neighbors: ["岡山県", "徳島県", "愛媛県"],
    specialties: ["讃岐うどん", "骨付鳥", "オリーブ"],
    spots: ["金刀比羅宮", "栗林公園", "小豆島"],
    relation: "日本で最も面積が小さい県。"
  },
  {
    id: 38,
    name: "愛媛県",
    reading: "Ehime",
    capital: "松山市",
    region: "四国",
    neighbors: ["広島県", "徳島県", "香川県", "高知県", "大分県", "山口県"],
    specialties: ["みかん", "今治タオル", "鯛めし"],
    spots: ["道後温泉", "松山城", "しまなみ海道"],
    relation: "みかんの生産が盛ん。"
  },
  {
    id: 39,
    name: "高知県",
    reading: "Kochi",
    capital: "高知市",
    region: "四国",
    neighbors: ["徳島県", "愛媛県"],
    specialties: ["カツオのたたき", "ゆず"],
    spots: ["桂浜", "四万十川", "高知城"],
    relation: "坂本龍馬の出身地。"
  },
  {
    id: 40,
    name: "福岡県",
    reading: "Fukuoka",
    capital: "福岡市",
    region: "九州",
    neighbors: ["山口県", "佐賀県", "熊本県", "大分県"],
    specialties: ["明太子", "博多ラーメン", "あまおう"],
    spots: ["太宰府天満宮", "糸島", "キャナルシティ博多"],
    relation: "九州地方で最も人口が多い。"
  },
  {
    id: 41,
    name: "佐賀県",
    reading: "Saga",
    capital: "佐賀市",
    region: "九州",
    neighbors: ["福岡県", "長崎県"],
    specialties: ["佐賀牛", "呼子のイカ"],
    spots: ["吉野ヶ里遺跡", "有田ポーセリンパーク", "唐津城"],
    relation: "有田焼などの陶磁器が有名。"
  },
  {
    id: 42,
    name: "長崎県",
    reading: "Nagasaki",
    capital: "長崎市",
    region: "九州",
    neighbors: ["佐賀県"],
    specialties: ["ちゃんぽん", "カステラ", "皿うどん"],
    spots: ["ハウステンボス", "グラバー園", "軍艦島"],
    relation: "島が非常に多い県。"
  },
  {
    id: 43,
    name: "熊本県",
    reading: "Kumamoto",
    capital: "熊本市",
    region: "九州",
    neighbors: ["福岡県", "大分県", "宮崎県", "鹿児島県"],
    specialties: ["馬刺し", "からし蓮根", "スイカ"],
    spots: ["熊本城", "阿蘇山", "黒川温泉"],
    relation: "阿蘇山のカルデラは世界最大級。"
  },
  {
    id: 44,
    name: "大分県",
    reading: "Oita",
    capital: "大分市",
    region: "九州",
    neighbors: ["福岡県", "熊本県", "宮崎県", "山口県", "愛媛県"],
    specialties: ["とり天", "関アジ・関サバ", "カボス"],
    spots: ["別府温泉", "由布院温泉", "九重“夢”大吊橋"],
    relation: "源泉数、湧出量が日本一で「おんせん県」と呼ばれる。"
  },
  {
    id: 45,
    name: "宮崎県",
    reading: "Miyazaki",
    capital: "宮崎市",
    region: "九州",
    neighbors: ["熊本県", "大分県", "鹿児島県"],
    specialties: ["マンゴー", "チキン南蛮", "宮崎牛"],
    spots: ["高千穂峡", "青島", "サンメッセ日南"],
    relation: "温暖な気候で、プロ野球のキャンプ地としても有名。"
  },
  {
    id: 46,
    name: "鹿児島県",
    reading: "Kagoshima",
    capital: "鹿児島市",
    region: "九州",
    neighbors: ["熊本県", "宮崎県", "沖縄県"],
    specialties: ["黒豚", "さつまいも", "白くま"],
    spots: ["桜島", "屋久島", "指宿温泉"],
    relation: "活火山の桜島や世界遺産の屋久島がある。"
  },
  {
    id: 47,
    name: "沖縄県",
    reading: "Okinawa",
    capital: "那覇市",
    region: "沖縄",
    neighbors: ["鹿児島県"],
    specialties: ["ゴーヤチャンプルー", "サーターアンダギー", "ちんすこう"],
    spots: ["美ら海水族館", "首里城", "国際通り"],
    relation: "かつて琉球王国として栄えた独自の文化を持つ。"
  }
];
